name: Lint and Format Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install black pylint

      # Auto-fix formatting issues with Black
      - name: Run Black (Auto-fix Formatting)
        run: black .

      # Run Pylint for Linting
      - name: Run Pylint
        run: |
          pylint $(git ls-files '*.py') --exit-zero
